[package]
name = "staverator"
version = "0.0.1"
authors = [
    "Jeron Aldaron Lau <jeronlau@plopgrizzly.com>",
    "Douglas Lau <doug.p.lau@gmail.com>"
]
edition.workspace = true
license = "GPL"

[dependencies]
devout = { workspace = true }
hatmil = { workspace = true }
sfff = { path = "../sfff" }
scof = { path = "../scof" }

[dependencies.ranch]
version = "0.2.1"
