[package]
name = "scorefall-ink"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Music composition software."
documentation = "https://docs.rs/scorefall"
readme = "README.md"
keywords = ["cross-platform", "gui", "scorefall", "music", "composition"]
categories = [
    "api-bindings",
    "data-structures",
    "encoding",
    "multimedia::audio",
    "multimedia",
]

[dependencies]
scof = { path = "../scof" }
