on: [push]
name: rustfmt
jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        tc: [nightly]
    steps:
    - uses: taiki-e/checkout-action@v1
    - uses: taiki-e/install-action@v2
    - run: rustup set profile minimal
    - run: rustup toolchain install ${{ matrix.tc }}
    - run: cargo +nightly fmt --all --check
