# ScoreFall Ink - Music Composition Software
#
# Copyright © 2019-2025 Jeryn Aldaron Lau <aldaronlau@gmail.com>
# Copyright © 2019-2025 Doug P. Lau
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation, either version 3 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.

[package]
name = "scorefall-ink-web"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "ink"
path = "src/mod.rs"

[dependencies]
devout = { workspace = true }
hatmil = { workspace = true }
wasm-bindgen = "0.2.104"
scof = { path = "../scof" }
staverator = { path = "../staverator" }
scorefall-ink = { path = "../ink" }

[dependencies.web-sys] # for building the GUI.
version = "0.3"
features = [
    "Document",
    "Element",
    "HtmlCollection",
    "UiEvent",
    "Window",
    "console",
]

[dependencies.human]
version = "0.2.0"

[dependencies.pasts]
version = "0.14.3"
features = ["web"]

[dependencies.async_main]
version = "0.4.0"
features = ["pasts"]

[dev-dependencies]
wasm-bindgen-test = "0.3.13"
